# Generated by Django 4.0.6 on 2022-07-23 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTutorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('document_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=19)),
                ('phone_number', models.CharField(max_length=20)),
                ('education_level', models.CharField(max_length=10)),
                ('autobiography', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'personal_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tutors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorsInterests',
            fields=[
                ('interest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestionTutorias.interests')),
            ],
            options={
                'db_table': 'tutors_interests',
                'managed': False,
            },
        ),
    ]
